### PR TITLE
#198 - Fix underscore in status pill of overview

### LINKED ISSUE #198: claim_requested and claim_approved shows underscore in label
### Expected behaviour
When a request has de status 'claim requested' or 'claim approved', in the overview, it shows a pill with as label 'claim requested' or 'claim approved'.

### Actual behaviour
It shows 'claim_requested' or 'claim_approved'.

### Steps to reproduce the behaviour
claim or approve a request and check the overview

### PR DESCRIPTION
**Pull request by nico-ptrs**
Fixes #198

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -219,3 +219,4 @@ core/docker_data
 **/node/**
 **/node_modules/**
 /tweb/src/main/frontend/src/js/contracts/
+**/frontend/package-lock.json
```
Comment (davyvanroy) [inline .gitignore]: this should be committed
https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

File: tweb/src/test/java/io/fundreqest/platform/tweb/request/dto/RequestDetailsViewMapperDecoratorTest.java [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+    public void map_null() {
+        final RequestDto requestDto = RequestDtoMother.fundRequestArea51();
+
+        when(delegate.map(requestDto)).thenReturn(null);
+
+        final RequestDetailsView result = decorator.map(requestDto);
+
+        assertThat(result).isNull();
+    }
+}
```
Comment (davyvanroy) [inline tweb/src/test/java/io/fundreqest/platform/tweb/request/dto/RequestDetailsViewMapperDecoratorTest.java]: afbeelding

File: .gitignore (hunk 1 above)
Comment (nico-ptrs) [reply .gitignore]: done
